### ISSUE TITLE
TODO in 56.2.1 View Option

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.aIPS#1]
### Contact Details

lduncan@path.org

### Section Number

56.2.1 View Option

### What is wrong

There is a TODO in this section that looks like it should possibly be an open issue for the public comment.

### Describe the solution you'd like

Determine if an open issues is the best place for this.

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by slagesse-epic** [comment]
My input for the question:

While Composition.text is optional, each Composition.section.text is mandatory. So I think the equivalent to what we have in CDA would be to require that Composition.section.text be rendered, and possibly also require the ability to render Composition.text if present.

**Comment by JohnMoehrke** [comment]
replace with requirement to display the Composition.section.text.
Add an Open-Issue
Log a improvement request with the greater IPS community.

**Comment by slagesse-epic** [comment]
Guidance in FHIR core:  http://hl7.org/fhir/documents.html#presentation
