### ISSUE TITLE
[Feature]: Describe how $summary Might Be Used Without Document Sharing Metadata

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.aIPS#5]
### Contact Details

slagesse@epic.com

### Is your feature request related to a problem? Please describe.

Given that the IPS is a patient level summary, and can be created by invoking the $summary operation, it is possible to exchange an IPS without conventional document sharing actors or working with document sharing objects. This would be done by simply having the Content Consumer invoke the $summary operation of the Content Creator. 

Implementations that are FHIR focused, and need only to exchange IPS and not other documents, would likely want to implement this solution, as it is the least complex. 

### Describe the solution you'd like

$summary should probably be considered an option for sharing the IPS along with the existing document sharing profiles. Linking this to the On-Demand concept and explaining the limitations of $summary (no ability to expand to additional documents) would also be helpful. 

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
point at the IPS $summary - http://hl7.org/fhir/uv/ips/OperationDefinition-summary.html
try to mention that the XDS on-demand is not the only way to use the $summary; that within other IGs it can be used directly as a FHIR Opertion by a client of that server.
